# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29c4ffb8d91ae16e509ba8bf664cac7fded50a723d8fcc96b35ca2669b7652a5bde3ead50c4ffa90e8206019637a23f27a82c0518b2b3e199f463e148094826b

test:
  secret_key_base: f962df1c10ddc4ffa5517259eca5abd3be8d1b53933552daa7a66afc6cc3ecaa07d49b58285f9b505aafb0e6460c058e89b6c2b4aba34795a169a2d6f69c78ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
