source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5.1'
# Use sqlite3 as the database for Active Record

# gem 'bootstrap-sass', '3.2.0.0'
# https://rubygems.org/gems/bootstrap-sass
# gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
# gem 'bootstrap-sass', '~> 3.3'
# Note [Update]
# gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
gem 'bootstrap-sass', '~> 3.3'

gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password

# gem 'bcrypt', '~> 3.1.7'
# https://rubygems.org/gems/bcrypt
# gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'bcrypt', '~> 3.1.11'

# Adding the Faker gem to the Gemfile
# gem 'faker', '1.4.2'
# https://rubygems.org/gems/faker
# gem 'faker', '~> 1.6', '>= 1.6.3'
# gem 'faker', '~> 1.6'
# Note [Update]
# gem 'faker', '~> 1.6', '>= 1.6.6'
gem 'faker', '~> 1.6'

# Including will_paginate in the Gemfile
# gem 'will_paginate', '3.0.7' 
# gem 'bootstrap-will_paginate', '0.0.10'
# https://rubygems.org/gems/will_paginate
# gem 'will_paginate', '~> 3.1', '>= 3.1.3'
gem 'will_paginate', '~> 3.1'
# https://rubygems.org/gems/bootstrap-will_paginate
gem 'bootstrap-will_paginate', '~> 0.0.10'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug'
  # gem 'byebug', github: 'deivid-rodriguez/byebug', branch: 'master'
  # https://rubygems.org/gems/byebug
  # gem 'byebug', '~> 9.0', '>= 9.0.5'
  # gem 'byebug', '~> 9.0'
  # Note [Update]
  # gem 'byebug', '~> 9.0', '>= 9.0.6'
  gem 'byebug', '~> 9.0'
  # https://github.com/colszowka/simplecov
  # gem 'simplecov', :require => false, :group => :test
  # https://rubygems.org/gems/simplecov/versions/0.12.0
  gem 'simplecov', '~> 0.12.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
